import { TrainerDetailsResponse } from './types';

export const mockTrainerDetails: Record<number, TrainerDetailsResponse> = {
  1: {
    isSuccess: false,
    code: "MOCK_DATA",
    message: "Failed to fetch trainer details, returning mock data.",
    result: {
      id: 1,
      realName: "김민수",
      age: 30,
      gender: "MALE",
      height: 178.5,
      weight: 75.2,
      region: "강남",
      gymName: "강남 피트니스 센터",
      badges: [
        {
          id: 101,
          badgeName: "근성왕",
          badgeDescription: "매일 5시간 이상 운동",
          iconUrl: "/images/badges/grit.png"
        }
      ],
      portfolios: [
        { id: 201, title: "체중 감량 성공", description: "6개월 만에 20kg 감량 성공" },
        { id: 202, title: "근력 향상 프로그램", description: "체계적인 근력 증가 트레이닝을 통한 성과" },
        { id: 203, title: "코어 강화 훈련", description: "복부 및 허리 근력을 향상시키는 트레이닝" },
        { id: 204, title: "하체 근력 강화", description: "스쿼트, 레그프레스, 런지 트레이닝으로 하체 근력 증진" },
        { id: 205, title: "유산소 훈련 및 마라톤 준비", description: "마라톤 준비를 위한 유산소 및 지구력 향상 훈련" },
        { id: 206, title: "올바른 자세 교정", description: "자세 불균형 교정을 위한 운동 및 피드백 제공" },
        { id: 207, title: "재활 트레이닝", description: "부상 후 회복을 위한 맞춤형 재활 운동 지도" },
        { id: 208, title: "웨이트 트레이닝 가이드", description: "웨이트 트레이닝 기초 및 단계별 운동 가이드 제공" },
        { id: 209, title: "스포츠 퍼포먼스 향상", description: "스포츠 선수들의 경기력을 높이기 위한 트레이닝" },
        { id: 210, title: "식단 및 영양 관리", description: "체중 조절 및 근육 증진을 위한 맞춤형 식단 설계" }
      ],
      members: [
        { id: 301, nickname: "헬린이1" }
      ]
    }
  },
  2: {
    isSuccess: false,
    code: "MOCK_DATA",
    message: "Failed to fetch trainer details, returning mock data.",
    result: {
      id: 2,
      realName: "박지훈",
      age: 35,
      gender: "MALE",
      height: 182.3,
      weight: 80.5,
      region: "서초",
      gymName: "서초 헬스장",
      badges: [{ id: 102, badgeName: "근육 마스터", badgeDescription: "웨이트 트레이닝 전문가", iconUrl: "/images/badges/muscle.png" }],
      portfolios: [{ id: 202, title: "근력 향상 트레이닝", description: "전문적인 근력 운동 루틴" }],
      members: [{ id: 302, nickname: "몸짱되자" }],
    },
  },
  3: {
    isSuccess: false,
    code: "MOCK_DATA",
    message: "Failed to fetch trainer details, returning mock data.",
    result: {
      id: 3,
      realName: "이준호",
      age: 28,
      gender: "MALE",
      height: 175.4,
      weight: 72.1,
      region: "송파",
      gymName: "송파 피트니스",
      badges: [
        { id: 103, badgeName: "코어 마스터", badgeDescription: "코어 운동 전문", iconUrl: "/images/badges/core.png" },
        { id: 104, badgeName: "스피드 킹", badgeDescription: "단거리 러닝 코치", iconUrl: "/images/badges/speed.png" },
      ],
      portfolios: [{ id: 203, title: "러닝 훈련 성공", description: "마라톤 참가자 훈련 과정" }],
      members: [{ id: 303, nickname: "달려라헬린이" }],
    },
  },
  4: {
    isSuccess: false,
    code: "MOCK_DATA",
    message: "Failed to fetch trainer details, returning mock data.",
    result: {
      id: 4,
      realName: "최성민",
      age: 40,
      gender: "MALE",
      height: 185.6,
      weight: 85.2,
      region: "강서",
      gymName: "강서 헬스센터",
      badges: [{ id: 105, badgeName: "파워리프팅 마스터", badgeDescription: "무거운 웨이트 리프팅 전문가", iconUrl: "/images/badges/power.png" }],
      portfolios: [
        { id: 204, title: "역도 대회 출전", description: "국내 역도 대회 우승 경험" },
        { id: 205, title: "체력 증진 트레이닝", description: "꾸준한 근력 운동 루틴" },
      ],
      members: [{ id: 304, nickname: "강해지고싶다" }],
    },
  },
  5: {
    isSuccess: false,
    code: "MOCK_DATA",
    message: "Failed to fetch trainer details, returning mock data.",
    result: {
      id: 5,
      realName: "정우성",
      age: 32,
      gender: "MALE",
      height: 176.2,
      weight: 74.3,
      region: "분당",
      gymName: "분당 퍼스트짐",
      badges: [{ id: 106, badgeName: "PT 1000회 달성", badgeDescription: "1000회 이상 PT 진행", iconUrl: "/images/badges/pt1000.png" }],
      portfolios: [{ id: 206, title: "체형 교정 프로그램", description: "바른 자세를 위한 트레이닝" }],
      members: [{ id: 305, nickname: "바른자세" }],
    },
  },
  6: {
    isSuccess: false,
    code: "MOCK_DATA",
    message: "Failed to fetch trainer details, returning mock data.",
    result: {
      id: 6,
      realName: "강민호",
      age: 29,
      gender: "MALE",
      height: 177.9,
      weight: 76.0,
      region: "일산",
      gymName: "일산 피트니스",
      badges: [{ id: 107, badgeName: "체중 감량 전문가", badgeDescription: "다이어트 전문 코치", iconUrl: "/images/badges/diet.png" }],
      portfolios: [{ id: 207, title: "다이어트 성공 사례", description: "체지방 감량 트레이닝" }],
      members: [{ id: 306, nickname: "다이어트성공" }],
    },
  },
  7: {
    isSuccess: false,
    code: "MOCK_DATA",
    message: "Failed to fetch trainer details, returning mock data.",
    result: {
      id: 7,
      realName: "조현우",
      age: 45,
      gender: "MALE",
      height: 180.3,
      weight: 79.8,
      region: "용산",
      gymName: "용산 헬스센터",
      badges: [{ id: 108, badgeName: "재활 운동 전문가", badgeDescription: "부상 회복 트레이닝", iconUrl: "/images/badges/rehab.png" }],
      portfolios: [{ id: 208, title: "재활 트레이닝 사례", description: "부상 후 회복 과정 공유" }],
      members: [{ id: 307, nickname: "부상회복중" }],
    },
  },
  8: {
    isSuccess: false,
    code: "MOCK_DATA",
    message: "Failed to fetch trainer details, returning mock data.",
    result: {
      id: 8,
      realName: "윤태민",
      age: 33,
      gender: "MALE",
      height: 174.8,
      weight: 73.5,
      region: "광진",
      gymName: "광진 퍼펙트짐",
      badges: [{ id: 109, badgeName: "필라테스 강사", badgeDescription: "필라테스 전문 트레이너", iconUrl: "/images/badges/pilates.png" }],
      portfolios: [{ id: 209, title: "필라테스 성공 사례", description: "유연성 향상 및 체형 교정" }],
      members: [{ id: 308, nickname: "필라테스러버" }],
    },
  },
  9: {
    isSuccess: false,
    code: "MOCK_DATA",
    message: "Failed to fetch trainer details, returning mock data.",
    result: {
      id: 9,
      realName: "오상혁",
      age: 38,
      gender: "MALE",
      height: 181.2,
      weight: 78.4,
      region: "강북",
      gymName: "강북 헬스 아카데미",
      badges: [
        { id: 110, badgeName: "올림픽 리프터", badgeDescription: "올림픽 리프팅 코치", iconUrl: "/images/badges/olympic.png" },
      ],
      portfolios: [
        { id: 210, title: "올림픽 리프팅 훈련", description: "국가대표 선수 훈련 지원" },
        { id: 211, title: "스포츠 재활", description: "부상 후 회복 프로그램" },
      ],
      members: [
        { id: 309, nickname: "강철맨" },
        { id: 310, nickname: "근력최고" },
      ],
    },
  },
  10: {
    isSuccess: false,
    code: "MOCK_DATA",
    message: "Failed to fetch trainer details, returning mock data.",
    result: {
      id: 10,
      realName: "배경호",
      age: 27,
      gender: "MALE",
      height: 176.5,
      weight: 73.1,
      region: "성동",
      gymName: "성동 퍼포먼스짐",
      badges: [
        { id: 111, badgeName: "바디빌딩 챔피언", badgeDescription: "보디빌딩 대회 1위 수상", iconUrl: "/images/badges/bodybuilding.png" },
      ],
      portfolios: [
        { id: 212, title: "보디빌딩 준비 과정", description: "대회 준비 및 식단 관리 노하우" },
        { id: 213, title: "초보자 맞춤 PT", description: "헬린이를 위한 맞춤형 PT 프로그램" },
      ],
      members: [
        { id: 311, nickname: "보디빌더꿈나무" },
        { id: 312, nickname: "초보탈출" },
      ],
    },
  },
};
