import { TiHomeOutline } from "react-icons/ti";
import { BsCart2 } from "react-icons/bs";
import { RiLightbulbFlashLine } from "react-icons/ri";
import { IoChevronBackOutline } from "react-icons/io5";
import { ReactComponent as Character } from "../assets/icons/potato_char.svg";
import { ReactComponent as EditRectangle } from "../assets/icons/edit_rectangle.svg";
import { ReactComponent as Profile } from "../assets/icons/default_profile.svg";
import { ReactComponent as GHealth } from "../assets/icons/Green_health.svg";
import { ReactComponent as BodyBoddy } from "../assets/icons/BODY BUDDY.svg";
import { ReactComponent as CheckMark1 } from "../assets/icons/checkMark-circle-gray.svg";
import { ReactComponent as CheckMark2 } from "../assets/icons/checkMark-circle-green.svg";
import { ReactComponent as CheckMark3 } from "../assets/icons/checkMark-circle-blue.svg";
import { ReactComponent as Title } from "../assets/icons/titleGroup.svg";
import { ReactComponent as Select } from "../assets/icons/select.svg";
import { ReactComponent as CalendarS } from "../assets/icons/calendar-select.svg";
import { ReactComponent as CalendarL } from "../assets/icons/calendar.svg";
import { ReactComponent as Logout } from "../assets/icons/LogoutLogo.svg";
import { ReactComponent as Exit } from "../assets/icons/ExitLogo.svg";
import { ReactComponent as TodoIcon1 } from "../assets/icons/TodoIcon-on.svg";
import { ReactComponent as TodoIcon2 } from "../assets/icons/TodoIcon-off.svg";
import { ReactComponent as CheckGreen } from "../assets/icons/check-button-green.svg";
import { ReactComponent as CheckGray } from "../assets/icons/check-button-gray.svg";
import { ReactComponent as RemoveGray } from "../assets/icons/remove-gray.svg";

export const PotatoImage = Character;
export const Edit = EditRectangle;
export const Logo = BodyBoddy;
export const CheckButton1 = CheckMark1;
export const CheckButton2 = CheckMark2;
export const CheckButton3 = CheckMark3;
export const TitleLoading = Title;
export const ArrowDown = Select;
export const HomeIcon = TiHomeOutline;
export const DefaultProfile = Profile;
export const GreenHealth = GHealth;
export const Cart = BsCart2;
export const Bulb = RiLightbulbFlashLine;
export const Back = IoChevronBackOutline;
export const CalendarIcon = CalendarL;
export const CalendarSelect = CalendarS;
export const ExitLogo = Exit;
export const LogoutLogo = Logout;
export const TodoIconOn = TodoIcon1;
export const TodoIconOff = TodoIcon2;
export const CheckButtonGray = CheckGray;
export const CheckButtonGreen = CheckGreen;
export const RemoveTodoButton = RemoveGray;
